BTL/Controllers/RoomController.cs
using BTL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using X.PagedList;

namespace BTL.Controllers
{
    public class RoomController : Controller
    {

		QlkhachSanAspContext db = new QlkhachSanAspContext();


		public IActionResult Index(int? page)
		{
			int pageSize = 3;
			int pageNumber = page == null || page < 0 ? 1 : page.Value;

			var lstLoaiPhong = db.LoaiPhongs.AsNoTracking().OrderBy(x => x.MaLp);

			PagedList<LoaiPhong> lst = new PagedList<LoaiPhong>(lstLoaiPhong, pageNumber, pageSize);
			return View(lst);
		}

        public IActionResult PhongTheoLoai(string maLoai, int? page)
        {
            int pageSize = 8;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;

			var phong = db.LoaiPhongs.Where(x => x.MaLp == maLoai).FirstOrDefault();
            ViewBag.Gia = phong.Gia;

            var lstPhong = db.Phongs.AsNoTracking().Where(x => x.MaLp == maLoai).OrderBy(x => x.MaLp);
            PagedList<Phong> lst = new PagedList<Phong>(lstPhong, pageNumber, pageSize);
            ViewBag.maloai = maLoai;
            return View(lst);
        }

        public IActionResult ChiTietPhong(string maphong, string maloai)
		{
			var Lphong = db.LoaiPhongs.SingleOrDefault(x => x.MaLp == maloai);

			var phong = db.Phongs.Where(x => x.MaPhong == maphong && x.MaLp == maloai).FirstOrDefault();

			ViewBag.TenPhong = phong.TenPhong;

			ViewBag.TinhTrang = phong.TinhTrang;

			var ctAnh = db.Ctanhs.Where(x => x.MaLp == maloai).ToList();
			ViewBag.ctAnh = ctAnh;

			return View(Lphong);
		}

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BTL/ViewComponents/LoaiPhongHomeMenuViewComponent.cs
using BTL.Models;
using Microsoft.AspNetCore.Mvc;
using BTL.Repository;
namespace BTL.ViewComponents
{
	public class LoaiPhongHomeMenuViewComponent : ViewComponent
	{
		private readonly ILoaiPhongRepository _loaiPhongRepository;
		public LoaiPhongHomeMenuViewComponent(ILoaiPhongRepository loaiPhongRepository)
		{
			_loaiPhongRepository = loaiPhongRepository;	
		}
		public IViewComponentResult Invoke()
		{
			var loaiPhong = _loaiPhongRepository.GetAll().OrderBy(x => x.LoaiPhong1);
			return View(loaiPhong);
		}
	}
}

BTL/ViewComponents/LoaiPhongRoomMenuViewComponent.cs
using BTL.Models;
using Microsoft.AspNetCore.Mvc;
using BTL.Repository;
namespace BTL.ViewComponents
{
	public class LoaiPhongRoomMenuViewComponent : ViewComponent
	{
		private readonly ILoaiPhongRepository _loaiPhongRepository;
		public LoaiPhongRoomMenuViewComponent(ILoaiPhongRepository loaiPhongRepository)
		{
			_loaiPhongRepository = loaiPhongRepository;
		}
		public IViewComponentResult Invoke() 
		{
			var loaiPhong = _loaiPhongRepository.GetAll().OrderBy(x => x.LoaiPhong1);
			return View(loaiPhong);
		}
	}
}

BTL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BTL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BTL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BTL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BTL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BTL/Views/Shared/_LayoutRoom.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
 <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Luxe &mdash; 100% Free Fully Responsive HTML5 Template by FREEHTML5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />

	<!--
	  //////////////////////////////////////////////////////

	  FREE HTML5 TEMPLATE
	  DESIGNED & DEVELOPED by FREEHTML5.CO

	  Website: 		http://freehtml5.co/
	  Email: 			info@freehtml5.co
	  Twitter: 		http://twitter.com/fh5co
	  Facebook: 		https://www.facebook.com/fh5co

	  //////////////////////////////////////////////////////
	   -->
	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">
	<!-- <link href='https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700italic,900,700,900italic' rel='stylesheet' type='text/css'> -->
	<!-- Stylesheets -->
	<!-- Dropdown Menu -->
	<link rel="stylesheet" href="../1Layout/css/superfish.css">
	<!-- Owl Slider -->
	<!-- <link rel="stylesheet" href="../1Layout/css/owl.carousel.css"> -->
	<!-- <link rel="stylesheet" href="../1Layout/css/owl.theme.default.min.css"> -->
	<!-- Date Picker -->
	<link rel="stylesheet" href="../1Layout/css/bootstrap-datepicker.min.css">
	<!-- CS Select -->
	<link rel="stylesheet" href="../1Layout/css/cs-select.css">
	<link rel="stylesheet" href="../1Layout/css/cs-skin-border.css">

	<!-- Themify Icons -->
	<link rel="stylesheet" href="../1Layout/css/themify-icons.css">
	<!-- Flat Icon -->
	<link rel="stylesheet" href="../1Layout/css/flaticon.css">
	<!-- Icomoon -->
	<link rel="stylesheet" href="../1Layout/css/icomoon.css">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="../1Layout/css/flexslider.css">

	<!-- Style -->
	<link rel="stylesheet" href="../1Layout/css/style.css">

	<!-- Modernizr JS -->
	<script src="../1Layout/../1Layout/js/modernizr-2.6.2.min.js"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="../1Layout/js/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<div id="fh5co-wrapper">
		<div id="fh5co-page">
			@await Html.PartialAsync("_PartialRoomHeader")
			<!-- end:fh5co-header -->
			<div class="fh5co-parallax" style="background-image: url(../1Layout/images/slider1.jpg);" data-stellar-background-ratio="0.5">
				<div class="overlay"></div>
				<div class="container">
					<div class="row">
						<div class="col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
							<div class="fh5co-intro fh5co-table-cell">
								<h1 class="text-center">Choose Your Room</h1>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<div id="fh5co-hotel-section">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="section-title text-center">
								<h2><a asp-controller="Room" asp-action="Index">Room List</a></h2>
								
							</div>
						</div>
					</div>
					<div id="displayRoom" class="row">
						@RenderBody()
					</div>
				</div>
			</div>


			@await Html.PartialAsync("_PartialFooter")

		</div>
		<!-- END fh5co-page -->

	</div>
	<!-- END fh5co-wrapper -->
	<!-- Javascripts -->
	<script src="../1Layout/js/jquery-2.1.4.min.js"></script>
	<!-- Dropdown Menu -->
	<script src="../1Layout/js/hoverIntent.js"></script>
	<script src="../1Layout/js/superfish.js"></script>
	<!-- Bootstrap -->
	<script src="../1Layout/js/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="../1Layout/js/jquery.waypoints.min.js"></script>
	<!-- Counters -->
	<script src="../1Layout/js/jquery.countTo.js"></script>
	<!-- Stellar Parallax -->
	<script src="../1Layout/js/jquery.stellar.min.js"></script>
	<!-- Owl Slider -->
	<!-- // <script src="../1Layout/js/owl.carousel.min.js"></script> -->
	<!-- Date Picker -->
	<script src="../1Layout/js/bootstrap-datepicker.min.js"></script>
	<!-- CS Select -->
	<script src="../1Layout/js/classie.js"></script>
	<script src="../1Layout/js/selectFx.js"></script>
	<!-- Flexslider -->
	<script src="../1Layout/js/jquery.flexslider-min.js"></script>

	<script src="../1Layout/js/custom.js"></script>

</body>
</html>

BTL/Views/Shared/_PartialFooter.cshtml
<footer id="footer" class="fh5co-bg-color">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<div class="copyright">
					<p>
						<small>
							&copy; 2016 Free HTML5 Template. <br> All Rights Reserved. <br>
							Designed by <a href="http://freehtml5.co" target="_blank">FreeHTML5.co</a> <br> Demo Images: <a href="http://unsplash.com/" target="_blank">Unsplash</a>
						</small>
					</p>
				</div>
			</div>
			<div class="col-md-6">
				<div class="row">
					<div class="col-md-3">
						<h3>Company</h3>
						<ul class="link">
							<li><a href="#">About Us</a></li>
							<li><a href="#">Hotels</a></li>
							<li><a href="#">Customer Care</a></li>
							<li><a href="#">Contact Us</a></li>
						</ul>
					</div>
					<div class="col-md-3">
						<h3>Our Facilities</h3>
						<ul class="link">
							<li><a href="#">Resturant</a></li>
							<li><a href="#">Bars</a></li>
							<li><a href="#">Pick-up</a></li>
							<li><a href="#">Swimming Pool</a></li>
							<li><a href="#">Spa</a></li>
							<li><a href="#">Gym</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<h3>Subscribe</h3>
						<p>Sed cursus ut nibh in semper. Mauris varius et magna in fermentum. </p>
						<form action="#" id="form-subscribe">
							<div class="form-field">
								<input type="email" placeholder="Email Address" id="email">
								<input type="submit" id="submit" value="Send">
							</div>
						</form>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<ul class="social-icons">
					<li>
						<a href="#"><i class="icon-twitter-with-circle"></i></a>
						<a href="#"><i class="icon-facebook-with-circle"></i></a>
						<a href="#"><i class="icon-instagram-with-circle"></i></a>
						<a href="#"><i class="icon-linkedin-with-circle"></i></a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer>

BTL/Views/Shared/_PartialHomeHeader.cshtml
<div id="fh5co-header">
	<header id="fh5co-header-section">
		<div class="container">
			<div class="nav-header">
				<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
				<h1 id="fh5co-logo"><a asp-action="Index">Luxe</a></h1>
				<nav id="fh5co-menu-wrap" role="navigation">
					<ul class="sf-menu" id="fh5co-primary-menu">
						<li><a class="active" asp-action="Index">Home</a></li>
						<li>
							<a asp-controller="Room" asp-action="Index" class="fh5co-sub-ddown">Room</a>
							<ul class="fh5co-sub-menu">
								@await Component.InvokeAsync("LoaiPhongHomeMenu")
							</ul>
						</li>
						<li><a asp-controller="">Services</a></li>
						<li><a asp-controller="">Blog</a></li>
						<li><a asp-controller="">Contact</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
</div>

BTL/Views/Shared/_PartialLoaiPhong.cshtml
@model LoaiPhong

<div class="feature-full-1col">
	<div class="image" style="background-image: url(@Url.Content("../images/" + Model.Anh));">
		<div class="descrip text-center">
			<p><small>For as low as</small><span>@Model.Gia/night</span></p>
		</div>
	</div>
	<div class="desc">
		<h3><a asp-controller="Room" asp-action="PhongTheoLoai" asp-route-maloai="@Model.MaLp">@Model.LoaiPhong1</a></h3>
		<p>@Model.ThongTin</p>
		<p>
			<a asp-controller="Room" asp-action="PhongTheoLoai" asp-route-maloai="@Model.MaLp" class="btn btn-primary btn-luxe-primary">Book Now <i class="ti-angle-right"></i></a>
		</p>
	</div>
</div>

BTL/Views/Shared/_PartialRoom.cshtml
@model Phong
<div class="col-md-4">
	<div class="hotel-content" >
		<div class="hotel-grid" style="background-image: url(@Url.Content("../images/" + Model.Anh));">
			<div class="price"><small>For as low as</small><span>@ViewBag.Gia/night</span></div>
			<a class="book-now text-center" href="#"><i class="ti-calendar"></i> Book Now</a>
		</div>
		<div class="desc">
			<h3><a asp-controller="Room" asp-action="ChiTietPhong" asp-route-maphong="@Model.MaPhong" asp-route-maloai="@Model.MaLp">@Model.TenPhong</a></h3>
            <p>@Model.TinhTrang</p>
		</div>
	</div>
</div>

BTL/Views/Shared/_PartialRoomHeader.cshtml
<div id="fh5co-header">
	<header id="fh5co-header-section">
		<div class="container">
			<div class="nav-header">
				<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
				<h1 id="fh5co-logo"><a asp-action="Index">Luxe</a></h1>
				<nav id="fh5co-menu-wrap" role="navigation">
					<ul class="sf-menu" id="fh5co-primary-menu">
						<li><a class="active" asp-controller="Home" asp-action="Index">Home</a></li>
						<li>
							<a asp-action="Index" class="fh5co-sub-ddown">Room</a>
							<ul class="fh5co-sub-menu">
								@await Component.InvokeAsync("LoaiPhongRoomMenu")
							</ul>
						</li>
						<li><a asp-controller="">Services</a></li>
						<li><a asp-controller="">Blog</a></li>
						<li><a asp-controller="">Contact</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
</div>